<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <RootNamespace>kServerManager</RootNamespace>
    <AssemblyName>kServerManager</AssemblyName>
    <Platforms>AnyCPU</Platforms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <NeutralLanguage>en</NeutralLanguage>

    <PublishUrl>publish\</PublishUrl>
    <ApplicationVersion>1.0.0.*</ApplicationVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="images\Folder-32.png" />
  </ItemGroup>

</Project>
